version: "3"

services:
    postgres_db:
        image: postgres
        container_name: 'postgres'
        volumes:
            - ./postgres_db:/var/lib/postgresql/data/
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env
        ports:
            - 5432:5432

    rabbitmq:
        image: rabbitmq
        restart: always
        container_name: 'app_rabbitmq'
        command: rabbitmq-server
        ports:
            - 15672:15672
            - 5672:5672
    computer_shop:
        container_name: 'computer_shop'
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: nest start computer-shop
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "5000:5000"
        depends_on:
            - rabbitmq
            - postgres_db

    pdf-saver:
        container_name: 'pdf-saver'
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: nest start pdf-saver
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - rabbitmq
            - postgres_db
volumes:
    postgres_db:
    static: